group=pl.Ljimex
version=0.0.1
description=OreFlow is a comprehensive Minecraft Spigot plugin that revolutionizes stone mining with configurable ore drops, Fortune enchantment support, craftable stone generators, and an intuitive GUI management system. 
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
